require 'app/lib/maps.rb'
require 'app/lib/path_tile.rb'
require 'app/lib/merge_sort_standard.rb'
require 'app/lib/merge_sort_precalc_heuristic.rb'
require 'app/lib/merge_sort_inline_precalc_heuristic.rb'

require 'app/lib/greedy_standard.rb'
require 'app/lib/greedy_merge_sort.rb'
require 'app/lib/greedy_sort_bang.rb'
require 'app/lib/greedy_path_tile.rb'
require 'app/lib/greedy_sort_bang_new_concat.rb'
require 'app/lib/greedy_sort_bang_precalc_heuristic.rb'
require 'app/lib/greedy_merge_sort_precalc_heuristic.rb'
require 'app/lib/greedy_merge_sort_precalc_heuristic_elm_ref.rb'
require 'app/lib/greedy_merge_sort_precalc_heuristic_new_concat.rb'
require 'app/lib/greedy_merge_sort_inline_precalc_heuristic_new_concat.rb'
